### ISSUE TITLE
Crash in Android IL2CPP build

### ISSUE THREAD

**Issue by ooonush** [FirstGearGames/FishNet#277]
Unity version: 2022.2 (and also 2021.3)
Fish-Networking version: 3.1.5

When I try to check if my NetworkBehaviour class has InjectAttribute attributes, when NetworkInitialize___Early comes in the loop, the game crashes on android if I use IL2CPP. At the same time with Scripting Backand = Mono and in the editor everything works fine. How to fix this problem?
Also, the game does not crash if you specify in IsDefined inherit = false.

```cs
foreach (var methodInfo in type.GetRuntimeMethods()) // type is NetworkBehaviour
{
    // Here, if there is a NetworkInitialize___Early method, the game crashes
    if (methodInfo.IsDefined(typeof(InjectAttribute), true))
    {
        // do...
    }
    // But if I remove inheritance in IsDefined, everything works
    if (methodInfo.IsDefined(typeof(InjectAttribute), false))
    {
        // do...
    }
}
```

**Expected behavior**

**Screenshots**

**Comment by FirstGearGames** [comment]
Update to the latest version please.

**Comment by ooonush** [comment]
It didn't help :(

**Comment by ooonush** [comment]
I reproduced this bag in [this Unity project](https://github.com/ooonush/FishNetBugReport) and made an apk build. Please see when you have the time.

**Comment by FirstGearGames** [comment]
You are trying to modify generated methods? Not sure what you are trying to accomplish.

**Comment by ooonush** [comment]
I check NetworkBehaviour class in foreach loop for methods with custom attribute. But the game crashes in IL2CPP build when I call methodInfo.IsDefined(typeof(CustomAttribute), true). I don't do anything with the generated method, the game crashes on the IsDefined method.

**Comment by FirstGearGames** [comment]
I don't know right away what could be causing this, but it sounds as though it's only crashing on generated methods.
The method you mentioned specifically is virtual, so that could be related.

Codegen sort of stuff is tricky with Unity and can quite literally break between any version. Adding reflection on-top of that over the generated methods is a recipe for disaster. Even if I were to fix this problem I'm sure it would behave differently or occur again in another engine version. Unfortunately I'm going to have to mark this as wontfix.
