### ISSUE TITLE
Strong jittering while using NetworkTransform component

### ISSUE THREAD

**Issue by bakwc** [FirstGearGames/FishNet#495]
**General**
Unity version: 2022.3.10
Fish-Networking version: 3.11.1R
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1161388839034703954

**Description**
Server object with attached NetworkTransform jittering very strong even on local connection.

**Replication**
1. Attach NetworkTransform
2. Spawn object on server

Actually there is a very simple example that reproduce behaviour: https://github.com/bakwc/reproduce_lag
Run one as server, another as a client.

**Expected behavior**
A smooth movement, no jittering

**Screenshots**

https://github.com/FirstGearGames/FishNet/assets/1684011/60b5bd0d-03fe-4741-b84f-420cf15ebb4c

**Comment by FirstGearGames** [comment]
I appreciate the repo project. At this time there are no known issues with the NetworkTransform smoothing. What you are seeing is most likely due to configuration or something else. I see you posted your problem but not much troubleshooting was performed.

While the repo is good if we need it later, we usually only look at repos under the most dire situations. Please debug more in our Discord. Show some movement code, NT settings, etc. If helpers are unable to identify the problem at that point go ahead and re-open this issue. Thanks!

**Comment by bakwc** [comment]
Now after switching to TimeManager physics the last issue that's not solved is jittering on the server and host side.
Clients now have a smooth movement, but in client + server (host) mode - the jittering presents.
I uploaded everything to a separate branch, `server_lag`:
https://github.com/bakwc/reproduce_lag/tree/server_lag

Client: Smooth movement
Server (Host): Jittering

Any advice?
