### ISSUE TITLE
Client stays connected on server when they exit the app in VR. 

### ISSUE THREAD

**Issue by mountainsquirrel2000** [FirstGearGames/FishNet#623]
# Important
If General, Description, and Replication are not completed the issue will be closed immediately.

**General**
Unity version:  2022.3.2011
Fish-Networking version: 3.11.18
Discord link:  https://discord.com/channels/424284635074134018/1129457538774073374/1218339495892746300
** Above, post a link from our Discord where you troubleshot the issue (on Discord click the three dots next to the message, then Copy Message Link). Issue may be closed out if this is not included.

**Description**
When I run the app on my headset, the player appears but when I quit the app, the player remains on the host.  If I reenter the app a new player is spawned and the old one can still be seen in the scene.  I've tested on my quest 2 and quest 3 headsets.   Behavior works fine when I test on computer using Parallel Sync.

**Replication**

Run server and client on computer then build and run on the headset.  Make sure to set Network Hud to auto launch in client mode for the headset.   Force exit the game on headset and see player still standing there on the server.

**Expected behavior**

Player exits when app is quit. 
[VRBugscene.zip](https://github.com/FirstGearGames/FishNet/files/14624954/VRBugscene.zip)

**Comment by TsFreddie** [comment]
Since the default Tugboat transport uses a UDP-based connection. There is no way of knowing when a client disconnect without it explicitly sending a disconnect signal, which a force exited client won't be able to do.

Unity Editor actually calls `OnDestroy` for all GameObjects upon exiting play mode which allows the transport to properly shutdown. While a build client might not have the ability to.

With this in mind. You can _try_ writing a [OnApplicationQuit()](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationQuit.html) hook or [Application.quitting](https://docs.unity3d.com/ScriptReference/Application-quitting.html) event, then find your `NetworkManager` to manually disconnect. However, these methods are not guaranteed to execute and may not have enough time to send out actual signals before the system kills your app.

As a fallback, you should configure a timeout strategy that is suitable for your need.

By default, FishNet is configured to timeout remote connection after 60 seconds. This might feels very long for your particular need. You can reduce that value in the `ServerManager` and `ClientManager` component.

**Comment by FirstGearGames** [comment]
TsFreddie is correct, this is not a bug. You can try to use StopConnection on the ClientManager to gracefully close the connection as well. But this behavior is normal, it's just how sockets work.

**Comment by mountainsquirrel2000** [comment]
The problem was the player never logs off even after time out.    After further testing this seems to only happen when I am testing locally on my computer with my vr as a client.    When I upload to a remote sever everything works as it should.   Its not that huge of an issue but it is still annoying when testing.

**Comment by FirstGearGames** [comment]
There is a timeout option on the servermanager where you can force it, without waiting for the transport.
