### ISSUE TITLE
NetworkCollider: Incorrect OnEnter invocation during reconcilliation replay.

### ISSUE THREAD

**Issue by aaronkwan** [FirstGearGames/FishNet#659]
**General**
Unity version: 2022.3.10f
Fish-Networking version: 4.2.2R
Discord link: https://discord.com/channels/424284635074134018/1234272046641319946/1234272046641319946

**Description**
- OnEnter sometimes invoked when OnStay should be instead. Occurs during the first playback of the reconciliation cycle.

**Replication**
- see discord link.

**Expected behavior**
- normal health prediction and reconciliation

**Actual behavior**
- janky health prediction and reconciliation (double damages)

**Screenshots**
- see discord link.

**Comment by FirstGearGames** [comment]
Confirmed. Even sitting still in the trigger/collider seems to cause issues.

**Comment by FirstGearGames** [comment]
I thought I was able to replicate by bumping the latency up significantly but I realized shortly after it's because the latency was exceeding the buffer on the NetworkTrigger.
![image](https://github.com/FirstGearGames/FishNet/assets/27169134/d5997dc8-1f72-4268-837f-1ee1cfb42356)
When the buffer is exceeded old states are dropped, thus the Entered state has been dropped.

Increasing the buffer beyond latency resolves the issue. If you are experiencing this while your latency is well below the History Duration please ping me in your thread so we can take a look together.

**Comment by FirstGearGames** [comment]
This issue is staying open until it can be confirmed as existing, or reasonably not existing. At this time there's not enough information to replicate the issue but it's still being worked on with a handful of individuals.

**Comment by FirstGearGames** [comment]
After testing and the efforts of many this issue is no longer reproducible on 4.3.5+. 

If the problem still persist for you please reach me on Discord FirstGearGames linking this issue so it can be re-opened. Either way though, I'll definitely need a test project.
